const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve('builder.html')).href);await page.evaluate(()=>document.fonts.ready);
const ids=await page.evaluate(()=>FOLIO_TEMPLATES.map(x=>x.id));assert.equal(ids.length,140);
for(const width of [1440,390]){await page.setViewportSize({width,height:1100});for(const id of ids){await page.evaluate(id=>{state=clone(defaults);selectTemplate(id);},id);assert.equal(await page.evaluate(()=>canvasOverflow),false,`Short CV overflow ${id} at ${width}`);const box=await page.evaluate(()=>{const p=document.querySelector('.a4-sheet');return [p.offsetWidth,p.offsetHeight];});assert.deepEqual(box,[794,1123]);}}
await page.setViewportSize({width:1440,height:1100});await page.evaluate(()=>{state=clone(defaults);renderFields();});
await page.selectOption('#canvas-pages','2');assert.equal(await page.locator('.a4-sheet').count(),2);await page.locator('#page-next').click();assert.match(await page.locator('#page-label').innerText(),/2 of 2/);await page.pdf({path:'cv-canvas-small-two.pdf',preferCSSPageSize:true,printBackground:true});
await page.evaluate(()=>{state.experience=Array.from({length:7},(_,i)=>({...defaults.experience[0],role:'Position '+i}));renderFields();});assert.equal(await page.evaluate(()=>canvasOverflow),false);const text=await page.locator('.paper-stage').textContent();for(let i=0;i<7;i++)assert(text.includes('Position '+i));await page.pdf({path:'cv-canvas-large-two.pdf',preferCSSPageSize:true,printBackground:true});
await page.selectOption('#canvas-pages','1');assert.equal(await page.locator('.a4-sheet').count(),1);assert.equal(await page.evaluate(()=>canvasOverflow),true);let printed=false;await page.exposeFunction('markPrinted',()=>{printed=true;});await page.evaluate(()=>window.print=()=>window.markPrinted());await page.locator('#export').click();assert.equal(printed,false);
await page.evaluate(()=>{state=clone(defaults);state.summary='A long description. '.repeat(350);state.canvas=normalizeCanvas({pages:2});renderFields();});assert((await page.locator('.paper-stage').textContent()).includes('A long description.'));assert.equal(await page.evaluate(()=>canvasOverflow),true);
await page.evaluate(()=>{state=clone(defaults);state.canvas=normalizeCanvas({pages:2});state.education=Array.from({length:4},(_,i)=>({...defaults.education[0],role:'Degree '+i}));state.projects=Array.from({length:4},(_,i)=>({role:'Project '+i,organization:'Lab',dates:'2026',description:'Developed an accessible application.'}));state.skills=Array.from({length:30},(_,i)=>'Skill '+i).join(', ');renderFields();});assert.equal(await page.evaluate(()=>canvasOverflow),false);await page.pdf({path:'cv-canvas-mixed.pdf',preferCSSPageSize:true,printBackground:true});
await page.evaluate(async photo=>{const image=new Image();image.src=photo;await image.decode();const canvas=document.createElement('canvas');canvas.width=480;canvas.height=480;canvas.getContext('2d').drawImage(image,0,0,480,480);state=clone(defaults);state.photo=canvas.toDataURL('image/jpeg',.85);renderFields();},'data:image/png;base64,'+fs.readFileSync('assets/sample-portrait.png').toString('base64'));
await page.locator('#cv-preview [data-block="summary"]').click();await page.fill('#block-width','90');await page.locator('#block-width').dispatchEvent('change');await page.fill('#block-size','12');await page.locator('#block-size').dispatchEvent('change');await page.locator('#block-bold').click();await page.fill('#canvas-margin','5');await page.locator('#canvas-margin').dispatchEvent('change');await page.locator('#zoom-out').click();const zoom=await page.locator('#zoom-label').innerText();await page.locator('#zoom-in').click();assert.notEqual(await page.locator('#zoom-label').innerText(),zoom);await page.reload();assert.equal(await page.evaluate(()=>state.canvas.blocks.summary.width),90);assert.equal(await page.evaluate(()=>state.canvas.blocks.summary.bold),true);await page.fill('[name="name"]','Updated Person');assert((await page.locator('#cv-preview').textContent()).includes('Updated Person'));await page.pdf({path:'cv-canvas-edited.pdf',preferCSSPageSize:true,printBackground:true});await page.screenshot({path:'studio-canvas-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:900});await page.screenshot({path:'studio-canvas-mobile.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: 140 templates at desktop/mobile; page modes; content flow; overflow export guard; image; styles; margins; zoom; persistence; live editing; PDF fixtures.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
